version: "3.8"
services:
  mysql:
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=example_pw
    volumes:
        - ./schema_files/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  flask:
    build: ./flask
    depends_on:
      - "mysql"
    ports:
      - "5000:5000"
